#!/bin/bash

set -e

 . config.sh


echo "+++ Add kernel config"
cat configs/GENERIC_WITH_ROOTFS.in | sed \
	-e s#\@CHERIBSD_ROOTFS_IMG\@#$CHERIBSD_ROOTFS_IMG#g \
	> cheribsd/sys/riscv/conf/GENERIC_WITH_ROOTFS

echo "+++ Build CheriBSD Kernel with rootfs"
pushd cheribsd 2>&1 >/dev/null

# force rebuild
touch sys/kern/init_main.c

MAKEOBJDIRPREFIX=$CHERIBSD_OBJDIRPREFIX CC=/usr/bin/clang CXX=/usr/bin/clang++ CPP=/usr/bin/clang-cpp STRIPBIN=/usr/bin/strip XCC=$CHERI_BIN_DIR/clang XCXX=$CHERI_BIN_DIR/clang++ XCPP=$CHERI_BIN_DIR/clang-cpp X_COMPILER_TYPE=clang XLD=$CHERI_BIN_DIR/ld.lld tools/build/make.py -j$(nproc) buildkernel TARGET=riscv TARGET_ARCH=riscv64c TARGET_CPUTYPE=cheri KERNCONF=GENERIC_WITH_ROOTFS -DDB_FROM_SRC -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH XLLVM_LINK=$CHERI_BIN_DIR/llvm-link LD=$CHERI_BIN_DIR/ld.lld XLD=$CHERI_BIN_DIR/ld.lld AR=$CHERI_BIN_DIR/llvm-ar NM=$CHERI_BIN_DIR/llvm-nm OBJCOPY=$CHERI_BIN_DIR/llvm-objcopy RANLIB=$CHERI_BIN_DIR/llvm-ranlib SIZE=$CHERI_BIN_DIR/llvm-size STRINGS=$CHERI_BIN_DIR/llvm-strings STRIPBIN=$CHERI_BIN_DIR/llvm-strip DEBUG=-g -DWITHOUT_CLEAN -DWITH_TESTS -DWITH_CHERI -DWITHOUT_INIT_ALL_ZERO -DWITHOUT_INIT_ALL_PATTERN -DWITHOUT_MAN -DWITHOUT_MAIL -DWITH_DISK_IMAGE_TOOLS_BOOTSTRAP -DWITHOUT_PROFILE -DWITHOUT_OFED -DWITH_MALLOC_PRODUCTION -DWITHOUT_GCC -DWITHOUT_CLANG -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -s -de

if [[ $? != 0 ]] ; then
	echo "------------ STOP"
	exit 1
fi

popd 2>&1 >/dev/null

echo "+++ Install CheriBSD Kernel with rootfs"
pushd cheribsd 2>&1 >/dev/null
MAKEOBJDIRPREFIX=$CHERIBSD_OBJDIRPREFIX CC=/usr/bin/clang CXX=/usr/bin/clang++ CPP=/usr/bin/clang-cpp STRIPBIN=/usr/bin/strip XCC=$CHERI_BIN_DIR/clang XCXX=$CHERI_BIN_DIR/clang++ XCPP=$CHERI_BIN_DIR/clang-cpp X_COMPILER_TYPE=clang XLD=$CHERI_BIN_DIR/ld.lld DESTDIR=$CHERIBSD_DESTDIR_KERNEL tools/build/make.py -j$(nproc) installkernel TARGET=riscv TARGET_ARCH=riscv64c TARGET_CPUTYPE=cheri -DDB_FROM_SRC -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH XLLVM_LINK=$CHERI_BIN_DIR/llvm-link LD=$CHERI_BIN_DIR/ld.lld XLD=$CHERI_BIN_DIR/ld.lld AR=$CHERI_BIN_DIR/llvm-ar NM=$CHERI_BIN_DIR/llvm-nm OBJCOPY=$CHERI_BIN_DIR/llvm-objcopy RANLIB=$CHERI_BIN_DIR/llvm-ranlib SIZE=$CHERI_BIN_DIR/llvm-size STRINGS=$CHERI_BIN_DIR/llvm-strings STRIPBIN=$CHERI_BIN_DIR/llvm-strip KERNCONF=GENERIC_WITH_ROOTFS DEBUG=-g NO_INSTALLEXTRAKERNELS=no -DINSTALL_KERNEL_DOT_FULL -DWITHOUT_CLEAN -DWITH_TESTS -DWITH_CHERI -DWITHOUT_INIT_ALL_ZERO -DWITHOUT_INIT_ALL_PATTERN -DWITHOUT_MAN -DWITHOUT_MAIL -DWITH_DISK_IMAGE_TOOLS_BOOTSTRAP -DWITHOUT_PROFILE -DWITHOUT_OFED -DWITH_MALLOC_PRODUCTION -DWITHOUT_GCC -DWITHOUT_CLANG -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -DWITH_KERNEL_SYMBOLS -s -de
popd 2>&1 >/dev/null

echo "+++ Extract and rename kernel+rootfs image"
rm -rf $FINAL_KERNEL_IMG
cp $CHERIBSD_DESTDIR_KERNEL/boot/kernel/kernel.full $FINAL_KERNEL_IMG # TODO: Do not use full kernel (only kernel), if no debugging symbols required
ls -lh $FINAL_KERNEL_IMG

echo "done."
